version: '3.8'

services:
  # PostgreSQL Database for development
  postgres-dev:
    image: postgres:15-alpine
    container_name: helpdesk-postgres-dev
    environment:
      POSTGRES_DB: helpdesk_dev
      POSTGRES_USER: helpdesk_user
      POSTGRES_PASSWORD: helpdesk_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - helpdesk-dev-network
    restart: unless-stopped

  # Redis for development
  redis-dev:
    image: redis:7-alpine
    container_name: helpdesk-redis-dev
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - helpdesk-dev-network
    restart: unless-stopped

  # Development database admin tool
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: helpdesk-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@helpdesk.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres-dev
    networks:
      - helpdesk-dev-network
    restart: unless-stopped

  # Redis admin tool
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: helpdesk-redis-commander
    environment:
      REDIS_HOSTS: local:redis-dev:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis-dev
    networks:
      - helpdesk-dev-network
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  helpdesk-dev-network:
    driver: bridge
